# Generated by Django 3.2.5 on 2022-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('satisfaction', models.BooleanField()),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('initial_answer', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
